.TH slick-greeter-set-keyboard-layout "1" "Sept 2017" "slick-greeter-set-keyboard-layout 1.0.8" "User Commands"
.SH NAME
slick-greeter-set-keyboard-layout \- switch keyboard layout
.SH DESCRIPTION
internal executable to switch the keyboard layout
.SH "SEE ALSO"
The full documentation for
.B slick-greeter-set-keyboard-layout
is maintained as a Texinfo manual.  If the
.B info
and
.B slick-greeter-set-keyboard-layout
programs are properly installed at your site, the command
.IP
.B info slick-greeter-set-keyboard-layout
.PP
should give you access to the complete manual.
